### PR TITLE
Fixed ctrl functionality with Aux and Edge lines

### PR DESCRIPTION
**Pull request by zaema-d**
*This pull request fixes the following issue*
* Fixes issue #337 

Added the necessary if conditions to LineColor.java file, fixing the ctrl functionality. Now the Aux and Edge lines functionality work as intended.

### CODE REVIEW

**Comment by zaema-d** [comment]
Hi @origamifaust this pr is ready for review.

**Comment by origamifaust** [comment]
Hi @zaema-d I just checked the pr, it's working perfectly fine :D

**Comment by TabLand** [comment]
Hi @zaema-d,

@origamifaust is learning to code at the moment and he's good at testing; it might be better to request a review from one of the project maintainers instead.

On first glance, there are too many files and lines changed - the commit needs to be redone to be less messy.

I'm currently travelling for other tasks this morning so can't build or review further, let's chat and walkthrough this PR together later this afternoon.

**Comment by undertrox** [comment]
It looks like your editor was set to a different format, maybe tabs vs spaces or different line endings, and automatically reformatted the entire project. That makes it almost impossible to review unfortunately, since your actual changes are buried somewhere between all the reformatting.
If you can undo the reformat, it would allow us to see the actual changes you made so we can review them

**Pull request closed without merging**
