### PR TITLE
Idk how many preference window tweak it's gonna get

### PR DESCRIPTION
**Pull request by Minh-Than**
- more compact window
- make it clear that the collapsible panel is collapsible (cursor pointer and bg change on hover)

image

### CODE REVIEW

**Comment by MuTsunTsai** [comment]
For the second point, I'd also suggest making the triangle icon bigger. What do you say?

**Comment by Minh-Than** [comment]
The triangle icon is actually a text haha, that's the biggest I can find that works for both ways (and different OS). I could use an actual icon somehow, which I'm not too well versed at. What are your suggestions?

**Comment by MuTsunTsai** [comment]
It certainly will look better by using an actual icon. @JuhoKonkkola should be able to help you on that.

**Comment by Minh-Than** [comment]
We'll I'd have to wait for him on what, should this PR wait until its finished or?

**Comment by MuTsunTsai** [comment]
Yeah we can merge this for now and work on the triangles later, I suppose.

**Pull request merged**
